### PR TITLE
Better translation

### PR DESCRIPTION
**Pull request by Johnmacrocraft**
Updated Korean translation, fixed some typos on English strings.

### CODE REVIEW

**Comment by Johnmacrocraft** [comment]
@FaigerSYS @IllegalerKater Someone should change _**image-loader.succesful**_ to _**image-loader.success**_ in deu.ini, I changed it on this pull request.

**Comment by IllegalerKater** [comment]
Ok why?

**Comment by Johnmacrocraft** [comment]
@IllegalerKater Simple. That's a typo

**Comment by Johnmacrocraft** [comment]
@FaigerSYS Please change _**선택**_ to _**클릭**_ on command.place.click~ (both) in kor.ini. Yeah I could create pull request again, but I think it's not worth to do it.

**Comment by Johnmacrocraft** [comment]
@FaigerSYS Also, is _**chunk**_ on instruction noun? If it's noun I changed it properly on English and Korean, but if it's verb I changed it wrongly.

**Comment by FaigerSYS** [comment]
Yeah, it's verb. Can you please create new PR with fixed translations?

**Comment by Johnmacrocraft** [comment]
@FaigerSYS Okay, I'll make new pull request as soon as possible.
Actually, I don't really understand what does chunk mean in verb, not noun. What did you want to say as that word? (Probably it means split, but I'm not sure so I should confirm this so I don't translate it wrongly)

**Comment by FaigerSYS** [comment]
@Johnmacrocraft Using the verb "chunk" I mean splitting the picture into several parts. Can it be used that way, or is it better to use another word?

**Comment by Johnmacrocraft** [comment]
@FaigerSYS I'm not native speaker so I'm not sure, but I think it can be changed to cut or split.

**Comment by Johnmacrocraft** [comment]
@FaigerSYS On _**image-loader.err-unsupported-api**_, does _**(and convert image again if didn't help)**_ explain previous sentence, or just bracket (?)?
Example to help understanding my question:
1. Hello, I'm (name) (and I love playing)!
2. _(Can't find any example)_

**Pull request merged**
