### PR TITLE
Support Korean

### PR DESCRIPTION
**Pull request by ParkChanSol**
Support Korean

### CODE REVIEW

**Comment by ParkChanSol** [comment]
@Johnmacrocraft 수정좀 해줘요. 하하하

**Comment by shdudwns** [comment]
@ParkChanSol 이거를 image넣고 /mie place 사진이름 auto 인가요?
*.jpg면 /mie place *.jpg auto 인가오ㅡ?

**Comment by FaigerSYS** [comment]
Can you tell me what you're talking about? 😅
@ParkChanSol change the download link to the old one, I'll release it later

**Comment by ParkChanSol** [comment]
@FaigerSYS 

@Johnmacrocraft reviewed "Umm. There seems to be something to modify."
@shdudwns 's comment plugin's usage. I think @shdudwns 's comment is a waste of words.

**Comment by ParkChanSol** [comment]
@shdudwns 저 팔로윙 취소하세요. 그리고 이건 그냥 잡다한 파일입니다. 플러그인 사용법은 제발 독학하세요;;

**Comment by FaigerSYS** [comment]
Thanks. Please change the download link and will merge PR

**Comment by ParkChanSol** [comment]
@FaigerSYS Change README

**Pull request merged**
